Add TensorFlow Lite implementation with test model
teamulster/soHappy pull request #11
Opened 2020-09-03 12:16 UTC by mac641

- TensorFlow Lite smile/emotion detection based on model is added in TFLiteImpl
- Basic TensorFlow Lite functions are added in abstract class TFLite
- Disable MagicNumber listing rule
- Add tests

-----------------------------------------

[Test model](https://github.com/mayurmadnani/fer)

2020-09-04 07:16 UTC, diehmlukas submitted a review, later dismissed

2020-09-04 07:35 UTC, AnnaGsell reviewed
Please add some comments to your code...

2020-09-04 10:19 UTC, AnnaGsell approved these changes

2020-09-04 10:29 UTC, craftamap requested changes
Good Work!

2020-09-04 10:29 UTC, craftamap commented on app/build.gradle
> +    implementation 'org.tensorflow:tensorflow-lite-task-vision:0.0.0-nightly'
Any reason to use the nightly-builds here? Are there stable builds available?

2020-09-04 10:29 UTC, craftamap commented on app/src/main/java/de/hsaugsburg/teamulster/sohappy/analyzer/detector/TFLite.kt
> +abstract class TFLite(tfliteModelPath: String, numberOfThreads: Int, activity: Activity) :
I'd suggest renaming this class to `AbstractTFLiteSmileDetector`.
After all, it is an smile detector, and not TFLite, right?

2020-09-04 10:29 UTC, craftamap commented on app/src/androidTest/java/de/hsaugsburg/teamulster/sohappy/SmileDetectorTest.kt
> +class SmileDetectorTest {
This does not test `SmileDetector`, does it? It should be named after the Implementation it does test.

2020-09-04 10:29 UTC, craftamap commented on app/src/main/java/de/hsaugsburg/teamulster/sohappy/analyzer/detector/TFLite.kt
> +        tfliteInterpreter.run(prepare(img), outputProbability.buffer.rewind())
I'd suggest to either put the result of `prepare(img)` and `outputProbability.buffer.rewind()` into their own variables before using, or at least to put them into their own line like this:
```kotlin 
tfliteInterpreter.run(
    prepare(img),
    outputProbability.buffer.rewind()
)
```
Either way, this would improve readability and debuggability.

2020-09-04 10:29 UTC, craftamap commented on app/src/main/java/de/hsaugsburg/teamulster/sohappy/analyzer/detector/TFLite.kt
> +        val maxResults: Int = 20
I don't think returning the top20 matches makes sense in our usecase, does it?

2020-09-04 10:29 UTC, craftamap commented on app/src/main/java/de/hsaugsburg/teamulster/sohappy/analyzer/detector/TFLite.kt
> +    private fun getTopMatches(labeledProbability: Map<String, Float>): ArrayList<Recognition> {
Is this function required at all? We just need top match, or all matches, right?

2020-09-04 10:29 UTC, craftamap commented on app/src/main/java/de/hsaugsburg/teamulster/sohappy/analyzer/detector/TFLite.kt
> +            val id: String, val title: String, val confidence: Float,
We do not use title and location, right?
In Line 87 you assign key to id as well as title, and null to location.

2020-09-04 10:29 UTC, craftamap commented on app/src/main/java/de/hsaugsburg/teamulster/sohappy/analyzer/detector/TFLiteImpl.kt
> +class TFLiteImpl(activity: Activity) :
Rename to `TFLiteSmileDetector`, and maybe even prepend it with the source, like `FerTFLiteSmileDetector`

2020-09-04 10:29 UTC, craftamap commented on app/src/main/java/de/hsaugsburg/teamulster/sohappy/analyzer/detector/TFLiteImpl.kt
> +            SmileDetector.Companion.SmileDetectionResult(true)
We should propably check if the confidence is over a certain threshold, if "Happy" has the highest confidence, but is still below 50%, its not happy, right?

2020-09-04 10:49 UTC, mac641 commented on app/build.gradle
> +    implementation 'org.tensorflow:tensorflow-lite-task-vision:0.0.0-nightly'
Not yet stable

2020-09-04 11:11 UTC, mac641 commented on app/src/main/java/de/hsaugsburg/teamulster/sohappy/analyzer/detector/TFLite.kt
> +    private fun getTopMatches(labeledProbability: Map<String, Float>): ArrayList<Recognition> {
Simplified function

2020-09-07 13:56 UTC, diehmlukas approved these changes
For the reading the abbreviations are not well

2020-09-07 13:57 UTC, merged