18 Implement config parser
teamulster/soHappy pull request #14
Opened 2020-09-04 09:47 UTC by mac641

2020-09-04 10:24 UTC, diehmlukas submitted a review, later dismissed

2020-09-05 12:20 UTC, AnnaGsell approved these changes

2020-09-07 07:07 UTC, craftamap commented on app/src/main/java/de/hsaugsburg/teamulster/sohappy/config/ConfigManager.kt
> +* This class parses configuration based on config.json.
This object*

2020-09-07 07:17 UTC, craftamap requested changes

2020-09-07 07:17 UTC, craftamap commented on app/src/main/java/de/hsaugsburg/teamulster/sohappy/config/ConfigManager.kt
> +    private fun parse(mainConfig: MainConfig): String {
don't call this function parse, it does not parse. It also does not the same as the other parse-function, but overloading does imply this.

I'd suggest `serialize` or `toJson`.

2020-09-07 07:17 UTC, craftamap commented on app/src/main/java/de/hsaugsburg/teamulster/sohappy/config/ConfigManager.kt
> +    fun load(context: Context) {
Not a necessary change, but I would suggest that load returns the MainConfig

2020-09-07 07:17 UTC, craftamap commented on app/src/main/java/de/hsaugsburg/teamulster/sohappy/config/ConfigManager.kt
> +        mainConfig = gson.fromJson<MainConfig>(jsonString, MainConfig::class.java)
Pretty sure that this will throw an exception if the json does not match the class.
Do you want to handle this?

2020-09-09 07:54 UTC, diehmlukas submitted a review, later dismissed

2020-09-09 07:58 UTC, diehmlukas approved these changes

2020-09-09 08:11 UTC, craftamap approved these changes

2020-09-09 08:19 UTC, AnnaGsell approved these changes

2020-09-09 08:20 UTC, merged