24 bitmap editor
teamulster/soHappy pull request #15
Opened 2020-09-04 10:01 UTC by diehmlukas

We fixed the tests and functions and also we added comments.

2020-09-04 11:03 UTC, craftamap approved these changes
Left some comments, which you can do, if you want to. Either way, good work! 🦚

2020-09-04 11:03 UTC, craftamap commented on app/src/main/java/de/hsaugsburg/teamulster/sohappy/analyzer/BitmapEditor.kt
> +        /**
```
@param frame is the rectangle you want to cut out. Note that the constructor of Rect takes right and bottom instead of height and width. right is the same as left+width and bottom is the same as top+height.
```

2020-09-04 11:41 UTC, mac641 requested changes
Looking good despite missing comments ^^

2020-09-04 11:41 UTC, mac641 commented on app/src/main/java/de/hsaugsburg/teamulster/sohappy/analyzer/BitmapEditor.kt
> +         * Right is the same as left+width and bottom is the same as top+height.
Make comment KDoc compliant.

2020-09-04 11:41 UTC, mac641 commented on app/src/main/java/de/hsaugsburg/teamulster/sohappy/analyzer/BitmapEditor.kt
> +    fun rotate(bitmap: Bitmap, degree: Float): Bitmap {
Missing comments

2020-09-07 07:20 UTC, craftamap submitted a review, later dismissed
Looks good to me! Please take a look at Marcel's comments, though!

2020-09-07 13:52 UTC, mac641 approved these changes

2020-09-07 13:52 UTC, mac641 commented on app/src/main/java/de/hsaugsburg/teamulster/sohappy/analyzer/BitmapEditor.kt
> +        val bitmap = bitmap.copy(Bitmap.Config.ARGB_8888, true)
Rename val bitmap - never override params

2020-09-07 14:07 UTC, mac641 approved these changes

2020-09-07 14:27 UTC, craftamap approved these changes

2020-09-07 14:27 UTC, craftamap approved these changes

2020-09-09 07:37 UTC, craftamap approved these changes

2020-09-09 07:37 UTC, AnnaGsell approved these changes

2020-09-09 07:38 UTC, merged