NO TICKET adapt detekt config
teamulster/soHappy pull request #19
Opened 2020-09-09 14:12 UTC by mac641

- Check detekt rules and set to true if useful
- Apply latest detekt rules changes
- Add Doc comments if necessary
- Minor refactoring

2020-09-09 17:24 UTC, AnnaGsell commented on app/src/androidTest/java/de/hsaugsburg/teamulster/sohappy/detector/FerTFLiteSmileDetectorImplTest.kt
> +            assertEquals(true, detectResult.isSmiling)
why not assertTrue for checking a boolean condition?

2020-09-09 17:26 UTC, AnnaGsell requested changes
nice job, but still have a look a the comments

2020-09-09 17:26 UTC, AnnaGsell commented on app/src/androidTest/java/de/hsaugsburg/teamulster/sohappy/detector/FerTFLiteSmileDetectorImplTest.kt
> +            assertEquals(true, detectResult.isSmiling)
why not assertTrue for checking a boolean condition?

2020-09-09 17:26 UTC, AnnaGsell commented on app/src/androidTest/java/de/hsaugsburg/teamulster/sohappy/detector/FerTFLiteSmileDetectorImplTest.kt
> +            assertEquals(false, detectResult.isSmiling)
same here

2020-09-10 07:34 UTC, craftamap approved these changes

2020-09-10 07:53 UTC, diehmlukas approved these changes

2020-09-10 07:53 UTC, AnnaGsell approved these changes

2020-09-10 07:56 UTC, merged