33 implement credits/privacy/imprint loader
teamulster/soHappy pull request #20
Opened 2020-09-10 13:06 UTC by mac641

- Add AboutConfig where credits/privacy/imprint URLs are stored
- Add AboutConfig loading in ConfigManager
- Adapt ConfigManagerTest
- Make detekt compliant

2020-09-10 13:13 UTC, craftamap approved these changes

2020-09-10 20:37 UTC, AnnaGsell requested changes

2020-09-10 20:37 UTC, AnnaGsell commented on app/src/main/java/de/hsaugsburg/teamulster/sohappy/config/ConfigManager.kt
> +     * This private function checks a given URL URL compliance.
URL twice in this sentence

2020-09-11 08:54 UTC, craftamap approved these changes

2020-09-11 08:56 UTC, AnnaGsell approved these changes

2020-09-11 09:20 UTC, merged