14 Added Implementation for self-trained model
teamulster/soHappy pull request #26
Opened 2020-09-15 08:54 UTC by craftamap

This implements the self-trained smile detector. More on the model after I published it.

2020-09-15 09:04 UTC, AnnaGsell submitted a review, later dismissed

2020-09-15 09:43 UTC, limkokyew reviewed
Two very minor issues, but other than that - good work!

2020-09-15 09:43 UTC, limkokyew commented on app/src/main/java/de/hsaugsburg/teamulster/sohappy/fragment/CameraFragment.kt
> +            //startCameraIfReady()
I'd suggest to either remove or uncomment this line.

2020-09-15 09:43 UTC, limkokyew commented on app/src/main/java/de/hsaugsburg/teamulster/sohappy/analyzer/detector/smiledetectorimpl/SoHappyTFLiteSmileDetector.kt
> +class SoHappyTFLiteSmileDetector(activity: Activity) :
KDoc is missing here.

2020-09-15 13:12 UTC, mac641 requested changes

2020-09-15 13:12 UTC, mac641 commented on app/src/main/java/de/hsaugsburg/teamulster/sohappy/analyzer/detector/smiledetectorimpl/SoHappyTFLiteSmileDetector.kt
> +        // TODO: This has to be adapted depending on each model
This TODO can be removed I guess 🤔

2020-09-15 13:13 UTC, diehmlukas submitted a review, later dismissed

2020-09-16 13:22 UTC, AnnaGsell submitted a review, later dismissed

2020-09-17 14:15 UTC, mac641 approved these changes

2020-09-17 14:16 UTC, merged