Added Logo
teamulster/soHappy pull request #29
Opened 2020-09-15 12:19 UTC by craftamap

2020-09-15 12:31 UTC, mac641 requested changes
Overall good icon 👍🏿  
Although I think it would look more natural if the mouth circle could be trimmed to some degree -> so that it does not stop next to the eyes.  
I suggest discussing this regard in the next meeting :)

2020-09-15 14:16 UTC, limkokyew submitted a review, later dismissed
Great logo! Regarding feedback, I would perhaps increase the padding between the circle outline and the smile.

2020-09-16 09:10 UTC, mac641 approved these changes
🚁

2020-09-16 09:10 UTC, diehmlukas approved these changes

2020-09-16 09:10 UTC, AnnaGsell approved these changes

2020-09-16 09:10 UTC, merged