Transformed StateMachine into ViewModel
teamulster/soHappy pull request #36
Opened 2020-09-16 10:37 UTC by craftamap

StateMaschine is now a ViewModel - this makes it much easier to use.

2020-09-16 10:51 UTC, mac641 requested changes

2020-09-16 10:51 UTC, mac641 commented on app/src/main/java/de/hsaugsburg/teamulster/sohappy/CameraActivity.kt
> +    internal val stateMachine: StateMachine by viewModels()
I'd suggest setting stateMachine *private*, since it is private in every other class

2020-09-16 10:51 UTC, mac641 commented on app/src/main/java/de/hsaugsburg/teamulster/sohappy/CameraActivity.kt
>      internal lateinit var localDatabaseManager : LocalDatabaseManager
It might worth checking if this could be set to private, too 😁

2020-09-16 10:55 UTC, AnnaGsell submitted a review, later dismissed

2020-09-16 11:26 UTC, mac641 submitted a review, later dismissed
👍🏿

2020-09-16 11:51 UTC, diehmlukas submitted a review, later dismissed

2020-09-16 13:23 UTC, AnnaGsell submitted a review, later dismissed

2020-09-17 10:34 UTC, mac641 submitted a review, later dismissed

2020-09-17 12:10 UTC, limkokyew submitted a review, later dismissed
Looks good to me!

2020-09-17 13:37 UTC, diehmlukas approved these changes

2020-09-17 13:57 UTC, mac641 approved these changes

2020-09-17 14:13 UTC, mac641 approved these changes

2020-09-17 14:15 UTC, diehmlukas approved these changes

2020-09-17 14:15 UTC, merged