Added Camera Functionality
teamulster/soHappy pull request #5
Opened 2020-09-01 14:34 UTC by craftamap

2020-09-02 07:39 UTC, mac641 requested changes

2020-09-02 07:39 UTC, mac641 commented on app/src/main/java/de/hsaugsburg/teamulster/sohappy/CameraActivity.kt
> +    private var bitmap: Bitmap? = null
add unified val/var order

2020-09-02 07:39 UTC, mac641 commented on app/src/main/java/de/hsaugsburg/teamulster/sohappy/CameraActivity.kt
> +    companion object {
add comments in whole code for better understanding

2020-09-02 12:56 UTC, limkokyew approved these changes
Looks good to me.

2020-09-03 07:35 UTC, AnnaGsell approved these changes

2020-09-03 07:43 UTC, diehmlukas approved these changes

2020-09-03 11:43 UTC, mac641 approved these changes
Comments looking good 👍🏿

2020-09-03 11:44 UTC, merged